PRODUCT_PACKAGES += \
	HardwareOverlayPicker \
	QtiAudio \
	TrebleApp \
	treble-overlay-NavBar \
	treble-overlay-NightMode \
	treble-overlay-SystemUI-FalseLocks \
	treble-overlay-Telephony-LTE \
	treble-overlay-caf-ims \
	treble-overlay-devinputjack \
	treble-overlay-realme-c21y \
	treble-overlay-duoqin-qin2pro \
	treble-overlay-essential-ph_1 \
	treble-overlay-fairphone-fp3 \
	treble-overlay-highpriomisc \
	treble-overlay-hw-ims \
	treble-overlay-lge-mfh505glm \
	treble-overlay-lge-mfh505glm-systemui \
	treble-overlay-lge-timelm \
	treble-overlay-mbi-s10 \
	treble-overlay-mbi-s10-systemui \
	treble-overlay-misc-aod \
	treble-overlay-misc-aod-systemui \
	treble-overlay-misc-dt2w \
	treble-overlay-misc-minimal-brightness \
	treble-overlay-mtk-ims \
	treble-overlay-realme-c3 \
	treble-overlay-sec-ims \
	treble-overlay-sprd-ims \
	treble-overlay-telephony-caf-ims \
	treble-overlay-telephony-hw-ims \
	treble-overlay-telephony-mtk-ims \
	treble-overlay-telephony-slsi-ims \
	treble-overlay-telephony-sprd-ims \
	treble-overlay-tethering \
	treble-overlay-tethering-nobpf \
	treble-overlay-unihertz-jelly2 \
	treble-overlay-wifi5g \
